/** WebP variants generated by `npm run optimize-images` */
export const images = {
  portrait: "/images/portrait.webp",
  photo01: "/images/photo-01.webp",
  photo02: "/images/photo-02.webp",
  photo03: "/images/photo-03.webp",
  mediaConsulting: "/images/media-consulting.webp",
  mediaSemiconductor: "/images/media-semiconductor.webp",
  mediaMa: "/images/media-ma.webp",
  mediaDentsu: "/images/media-dentsu.webp",
  mediaCareer: "/images/media-career.webp",
  mediaBook: "/images/media-book.webp",
  mediaCambria: "/images/media-cambria.webp",
  mediaTalk: "/images/media-talk.webp",
} as const;
